# tag: 9.3-minimal-19700101
FROM quay.io/ykohut/9-minimal:9

LABEL maintainer="AlmaLinux OS Foundation"
LABEL summary="Provides a AlmaLinux 9 minimal container."
LABEL description="An Open Source, community owned and governed, forever-free enterprise Linux distribution, focused on long-term stability, providing a robust production-grade platform. AlmaLinux OS is binary compatible with RHEL"
