name: AlmaLinux 8 and 9, Container/Docker Images builder and uploader (to Docker Hub)

on:
    workflow_dispatch:
        inputs:
          major_version:
            description: 'AlmaLinux major version'
            required: true
            default: '9'
            type: choice
            options:
              - 9
              - 8

          platform:
            description: 'Comma-separated list of platforms: "linux/amd64", "linux/ppc64le", "linux/s390x", "linux/arm64"'
            required: true
            default: '"linux/amd64", "linux/ppc64le", "linux/s390x", "linux/arm64"'

          image_types:
            description: 'Comma-separated list of image type(s): "default", "minimal", "micro", "base", "init"'
            required: true
            default: '"default", "minimal", "micro", "base", "init"'
 
          push:
            description: 'Push to DockerHub'
            required: true
            type: boolean

env:
  VERSION_MINOR: ${{ inputs.major_version == '9' && '3' || '9' }}
  REGISTRY_IMAGE: ykohut/almalinux

jobs:
  build:
    name: "Build for ${{ inputs.major_version }} ${{ matrix.image_types }} ${{ matrix.platform }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(format('[{0}]', inputs.platform || '"linux/amd64", "linux/ppc64le", "linux/s390x", "linux/arm64"')) }}
          # - linux/amd64
          # - linux/ppc64le
          # - linux/s390x
          # - linux/arm64

        image_types: ${{ fromJSON(format('[{0}]', inputs.image_types || '"default", "minimal", "micro", "base", "init"')) }}
          # - default
          # - minimal
          # - micro
          # - base
          # - init
    steps:
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          image_types=${{ matrix.image_types }}
          echo "IMAGE_TYPES_PAIR=${image_types//\//-}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:dockerfiles/al${{ inputs.major_version }}/${{ matrix.image_types }}"
          platforms: ${{ matrix.platform }}
          # labels: ${{ steps.meta.outputs.labels }}
          # tags: ${{ steps.meta.outputs.tags }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=${{ inputs.push }}
      -
        name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      -
        name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}-${{ env.IMAGE_TYPES_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: "Push for ${{ inputs.major_version }} ${{ matrix.image_types }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_types: ${{ fromJSON(format('[{0}]', inputs.image_types || '"default", "minimal", "micro", "base", "init"')) }}

    needs:
      - build
    steps:
      -
        name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*${{ matrix.image_types }}
          merge-multiple: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          # Set 'letest' tag for AlmaLinux 9 default image
          # Set '8'/'9' and 8.9/9.3 tags for AlmaLinux 8 or 9 and default image
          tags: |
            type=raw,priority=500,value=latest,enable=${{ matrix.image_types == 'default' && inputs.major_version == '9'  }}
            type=raw,priority=400,value=${{ inputs.major_version }},enable=${{ matrix.image_types == 'default' }}
            type=raw,priority=300,value=${{ inputs.major_version }}.${{ env.VERSION_MINOR }},enable=${{ matrix.image_types == 'default' }}
            type=raw,priority=200,value=${{ inputs.major_version }}-${{ matrix.image_types }},enable=${{ matrix.image_types != 'default' }}
            type=raw,priority=100,value=${{ inputs.major_version }}.${{ env.VERSION_MINOR }}-${{ matrix.image_types }},enable=${{ matrix.image_types != 'default' }}

          labels: |
            maintainer=Yuriy Kohut <ykohut@almalinux.org>
            org.opencontainers.image.title=${{ inputs.major_version }}.${{ env.VERSION_MINOR }}-${{ matrix.image_types }}
            org.opencontainers.image.description=Almalinux ${{ inputs.major_version }}.${{ env.VERSION_MINOR }} ${{ matrix.image_types }} for ${{ matrix.platform }}
            org.opencontainers.image.vendor=AlmaLinux
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}