name: AlmaLinux 8 and 9, Container/Docker Images builder and uploader (to docker Hub)

on:
    workflow_dispatch:
        inputs:
          major_version:
            description: 'AlmaLinux major version'
            required: true
            default: '9'
            type: choice
            options:
              - 9
              - 8
          # minor_version:
          #   description: 'AlmaLinux minor version'
          #   required: true
          #   default: '3'
          #   type: choice
          #   options:
          #     - 0
          #     - 1
          #     - 2
          #     - 3
          #     - 4
          #     - 5
          #     - 6
          #     - 7
          #     - 8
          #     - 9
          image_types:
            description: 'Image type(s) to build'
            required: true
            default: 'minimal'
            type: choice
            options:
              - default
              - minimal
              - micro
              - base
              - init
          push:
            description: 'Push to DockerHub'
            required: true
            type: boolean

env:
  VERSION_MINOR: ${{ inputs.major_version == '9' && '3' || '9' }}
  REGISTRY_IMAGE: ykohut/almalinux

jobs:
  build:
    name: "Buil and Push ${{ inputs.major_version }} ${{ inputs.image_types }} ${{ matrix.platform }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          # - linux/ppc64le
          # - linux/s390x
          # - linux/arm64

        # image_types:
        #   - default
        #   - minimal
        #   - micro
        #   - base
        #   - init
    steps:
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:dockerfiles/al${{ inputs.major_version }}/${{ inputs.image_types }}"
          platforms: ${{ matrix.platform }}
          # labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=${{ inputs.push }}
      -
        name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      -
        name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      -
        name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          # Set 'letest' tag for AlmaLinux 9 default image
          # Set '8' or '9' tag for AlmaLinux 8 or 9 and default image
          tags: |
            type=raw,value=latest,enable=${{ inputs.image_types == 'default' && inputs.major_version == '9'  }}
            type=raw,value=${{ inputs.major_version }},enable=${{ inputs.image_types == 'default' && inputs.major_version == '9' || inputs.major_version == '8' }}
            type=raw,value=${{ inputs.major_version }}-${{ inputs.image_types }}
            type=raw,value=${{ inputs.major_version }}.${{ env.VERSION_MINOR }}-${{ inputs.image_types }}

          labels: |
            maintainer=Yuriy Kohut <ykohut@almalinux.org>
            org.opencontainers.image.title=${{ inputs.major_version }}.${{ env.VERSION_MINOR }}-${{ inputs.image_types }}
            org.opencontainers.image.description=Almalinux ${{ inputs.major_version }}.${{ env.VERSION_MINOR }} ${{ inputs.image_types }} for ${{ matrix.platform }}
            org.opencontainers.image.vendor=AlmaLinux

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}